name: Auth Service CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build-test-security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run Tests
        run: |
          cd auth-service
          go test ./...

      - name: Build
        run: |
          cd auth-service
          go build ./...

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .

  publish:
    runs-on: ubuntu-latest

    needs: build-test-security

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          cd auth-service
          docker build -t auth-service:${{ github.sha }} .

      - name: Tag Image
        run: |
          docker tag auth-service:${{ github.sha }} 574349219641.dkr.ecr.us-east-1.amazonaws.com/auth-service:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push 574349219641.dkr.ecr.us-east-1.amazonaws.com/auth-service:${{ github.sha }}

  update-gitops:
    runs-on: ubuntu-latest

    needs: publish

    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: rcrrocha/togglemaster-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update Image Tag
        run: |
          sed -i 's|image: .*|image: 574349219641.dkr.ecr.us-east-1.amazonaws.com/auth-service:${{ github.sha }}|g' gitops/apps/auth/deployment.yaml

      - name: Commit Changes
        run: |
          cd gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add apps/auth/deployment.yaml

          git commit -m "Update auth-service image to ${{ github.sha }}" || echo "No changes"

          git push origin HEAD:main
